In [3]:
import numpy as np
import pandas as pd
from sklearn import linear_model

In [2]:
df=pd.read_csv("House.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [4]:
import math
med_bed =math.floor(df.bedrooms.median())
med_bed

4

In [5]:
df.bedrooms = df.bedrooms.fillna(med_bed)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [6]:
reg = linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [7]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [25]:
reg.intercept_

221323.00186540443

In [8]:
reg.predict([[3000,3,40]])

array([498408.25158031])

In [30]:
reg.predict([[2500,4,5]])

array([578876.03748933])

In [34]:
112.06244194*3000+23388.88007794*3-3231.71790863*40+221323.00186540443

498408.25157402444

In [14]:
#Exercise of hiring.csv
from word2number import w2n
df1=pd.read_csv('hiring.csv')
df1


experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [15]:
df1.experience = df1.experience.fillna('zero')
df1

experience  test_score  interview_score  salary
0       zero         8.0                9   50000
1       zero         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000
5      three         7.0               10   62000
6        ten         NaN                7   72000
7     eleven         7.0                8   80000

In [16]:
df1.experience = df1.experience.apply(w2n.word_to_num)
df1

experience  test_score  interview_score  salary
0           0         8.0                9   50000
1           0         8.0                6   45000
2           5         6.0                7   60000
3           2        10.0               10   65000
4           7         9.0                6   70000
5           3         7.0               10   62000
6          10         NaN                7   72000
7          11         7.0                8   80000

In [18]:
import math
tests = math.floor(df1.test_score.median())
tests

8

In [19]:
df1.test_score = df1.test_score.fillna(tests)
df1.test_score

0     8.0
1     8.0
2     6.0
3    10.0
4     9.0
5     7.0
6     8.0
7     7.0
Name: test_score, dtype: float64

In [23]:
reg1 = linear_model.LinearRegression()
reg1.fit(df1[['experience','test_score','interview_score']],df1.salary)



LinearRegression()

In [ ]:
#y=m1*x1 + m2*x2 + m3*x3 + b

In [27]:
reg1.intercept_

17737.26346433768

In [29]:
reg1.coef_

array([2812.95487627, 1845.70596798, 2205.24017467])

In [31]:
2812.95487627*2 + 1845.70596798*9 +  2205.24017467*6 + 17737.26346433768


53205.967976717686

In [34]:
reg1.predict([[2,9,6]])

array([53205.96797671])

In [35]:
reg1.predict(([[12,10,10]]))

array([92002.18340611])